/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * t2Report_2.java
 *
 * Created on 20 Sep, 2015, 8:04:15 AM
 */

package attendancesystem;

/**
 *
 * @author pc
 */
import java.sql.*;
import javax.swing.*;
public class t2Report_2 extends javax.swing.JFrame {

    /** Creates new form t2Report_2 */
    public t2Report_2() {
        initComponents();
    }
    DefaultListModel l1=new DefaultListModel();

    String username,password,semester,branch,subject,subjid,teacherid;
    public void getdata_ViewRecord(String uname,String pwd,String sem,String b,String subj,String subjid,String trid )
    {
        username=uname;
        password=pwd;
        semester=sem;
        branch=b;
        subject=subj;
        teacherid=trid;
//        System.out.println("-----------");
//        System.out.println(username+password+semester+branch+subj);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b1.setText("Logout");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(14, 14, 14)
                        .addComponent(b1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        t2AddRecord a1=new t2AddRecord();
        a1.getdata_teacher1(username,password);
        a1.setVisible(rootPaneCheckingEnabled);
        this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(rootPaneCheckingEnabled);
        this.dispose();
}//GEN-LAST:event_b1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
            //   list1.setModel(l1);
        try
       {
        //l1.addElement("ID------NAME----SEM--BRANCH--STATUS---Date");
        AccessConnect a1=new AccessConnect();
        Statement st=a1.connecttoSAS();
        String s3="select s.sid,s.sname,s.semester,s.sbranch,t.tid,t.subjid,t.status,t.p_date from student s inner join attendance t on s.sid=t.sid inner join subject a on a.tid=t.tid";
        ResultSet rs=st.executeQuery(s3);
        while(rs.next())
        {
            int sid1=rs.getInt("sid");
            String sname1=rs.getString("sname");
            sname1=sname1.trim();
            int tr_id=rs.getInt("tid");
            int s=rs.getInt("subjid");
            int status=rs.getInt("status");
            int sem=rs.getInt("semester");
            String b=rs.getString("sbranch");
            b=b.trim();
            String stat="";
            if(status==0)
            {
                stat="Absent";
            }
            else
            {
                stat="Present";
            }
            Date dt=rs.getDate("p_date");
            String date=""+dt;
            if(Integer.parseInt(semester)==sem && branch.equalsIgnoreCase(b) && tr_id==Integer.parseInt(teacherid))
            {
                System.out.println(sid1+sname1+stat+sem+b+date);
                l1.addElement(sid1+"    "+sname1+"  SEM:"+sem+"  "+b+"    "+stat+"   "+date);

            }
        }
        list1.setModel(l1);
        //System.out.println("hogya2");
        }catch(Exception e){}
    }//GEN-LAST:event_formComponentShown

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new t2Report_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list1;
    // End of variables declaration//GEN-END:variables

}
