/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * t3AddRecord_2.java
 *
 * Created on 20 Sep, 2015, 7:30:19 AM
 */

package attendancesystem;

/**
 *
 * @author pc
 */
import java.sql.*;
import java.util.*;
import javax.swing.*;
public class t3AddRecord_2 extends javax.swing.JFrame {

    /** Creates new form t3AddRecord_2 */
    public t3AddRecord_2() {
        initComponents();
    }
    DefaultListModel l1=new DefaultListModel();
    String semester,branch,subject,username,password;
    int studentid,subjectid,teacherid;
    public void getdata_AddRecord(String sem,String b,String subj,String uname,String pwd,int t_id)
    {
        semester=sem;
        branch=b;
        subject=subj;
        username=uname;
        password=pwd;
        teacherid=t_id;
        System.out.println(semester+branch+subject);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        b2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        b1.setText("Logout");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list);

        b2.setText("Present");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b3.setText("Absent");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b2)
                        .addGap(13, 13, 13)
                        .addComponent(b3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(14, 14, 14)
                        .addComponent(b1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(jButton1)
                    .addComponent(b2)
                    .addComponent(b3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
          String sname=""+list.getSelectedValue();
          String sid=sname.substring(0, 3);
          studentid=Integer.parseInt(sid);
          int status=1;
          try
           {
               AccessConnect a1=new AccessConnect();
               Statement st=a1.connecttoSAS();
               String s1="insert into attendance (sid,subjid,status) values('"+studentid+"','"+subjectid+"','"+status+"')";
               System.out.println("----------");
               int i=st.executeUpdate(s1);
               System.out.println(i);
               l1.removeElement(sname);
               list.setModel(l1);
           }
           catch(Exception e){}
    }//GEN-LAST:event_b2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        t2AddRecord a1=new t2AddRecord();
        a1.getdata_teacher1(username,password);
        a1.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try
       {
        AccessConnect a1=new AccessConnect();
        Statement st=a1.connecttoSAS();
        String s2="select s.sid,s.sname,s.sbranch,s.semester,t.subjid,t.subjname from student s inner join subject t on s.semester=t.sem inner join teacher a on a.tid=t.tid where a.tid='"+teacherid+"'";
        
        ResultSet rs1=st.executeQuery(s2);
        while(rs1.next())
        {
            int sid=rs1.getInt("sid");
            studentid=sid;
            int subjid=rs1.getInt("subjid");
            String sname=rs1.getString("sname");
            sname=sname.trim();
            String b=rs1.getString("sbranch");
            b=b.trim();
            String subj=rs1.getString("subjname");
            subj=subj.trim();
            int sem=rs1.getInt("semester");
            System.out.println("------------");
            System.out.println(sid+sname+subj+sem);
            if(Integer.parseInt(semester)==sem && branch.equalsIgnoreCase(b) && subject.equalsIgnoreCase(subj))
            {
               l1.addElement(sid+")"+sname);
               subjectid=subjid;
            }
        }
        list.setModel(l1);
        list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        System.out.println("hogya10");
        }catch(Exception e){}
    }//GEN-LAST:event_formComponentShown

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        String sname=""+list.getSelectedValue();
          String sid=sname.substring(0, 3);
          studentid=Integer.parseInt(sid);
          int status=0;
          try
           {
               AccessConnect a1=new AccessConnect();
               Statement st=a1.connecttoSAS();
               String s1="insert into attendance (sid,subjid,status) values('"+studentid+"','"+subjectid+"','"+status+"')";
               System.out.println("----------");
               int i=st.executeUpdate(s1);
               System.out.println(i);
               l1.removeElement(sname);
               list.setModel(l1);
           }
           catch(Exception e){}
    }//GEN-LAST:event_b3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new t3AddRecord_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    // End of variables declaration//GEN-END:variables

}
